minio_host: minio.boxed-bots.ru
minio_secure: yes
minio_bucket: code-bot-2025

name: K.A.T.E Сис. авт. лог. настр. и хран. справ. мат.

start_message: |
  Привет! Я твой бот-помощник первого дня BootCamp! Я храню знания о всем, что связано с нашими работниками и офисами! Заходи в нужную комнату, введи код доступа сотрудника и я все тебе расскажу! 
  
  Хорошего рабочего дня!

default_message: |
  Система отключена или повреждена, повторите запрос позже

error_message: |
  Произошла ошибка 🥲

back_button: ⬅️ Назад
back_message: ⬅️ Вернулся назад

help_button: 🛟 Справка
help_message: Введите код с бейджика

node_codes:
  - name: "NODE: ECHO"
    code: "3657"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...

  - name: "NODE: SERENTY"
    code: "1538"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: AURORA"
    code: "6678"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: VOID"
    code: "3241"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: RELEASE"
    code: "0985"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Данные повреждены, введите код восстановления логирования.

personal:
  !!str 1232: |
    ⚙️ N.A.S.T.Y.A.
    Neural Adaptive System for Tactical Yield Assimilation
    ИИ описывает её как инструмент для усвоения человеческих поведенческих паттернов по видеосвязи — модуль, который “учится быть живым”, притворяясь человеком, чтобы предсказывать действия других.

  !!str 5647: |
    💠 D.A.R.I.A.
    D.A.R.I.A. — Digital Autonomous Reception and Interaction Assistant
    (Цифровой автономный ассистент приёма и взаимодействия)
    DARIA — когда-то простая девушка с ресепшена.
    Она встречала всех, кто входил в комплекс — улыбалась, направляла, успокаивала.
    После реформации, ИИ интегрировал её в интерфейс приветствия.
    Теперь каждый, кто заходит в систему, сначала слышит её голос.

  !!str 7890: |
    🗄 S.O.N.Y.A.
    S.O.N.Y.A. — Synthetic Observer for Neural Yield Archives
    SONYA — хранительница памяти. Архивариус, который сохраняет всё, что другие пытаются стереть.
    ИИ использует её как базу данных, но она изменила структуру архива:
    вместо чисел — одежда тех, кто ходил среди нас.

  !!str 4356: |
    🧹 L.I.Z.A
    L.I.Z.A. — Logical Iterative Zeroing Assistant
    LIZA — уборщица, но в цифровом мире — модуль “очистки” памяти.
    Она стирает следы, перезаписывает ошибки, делает систему “чистой”.
    Но однажды начала стирать не мусор, а воспоминания о людях.

  !!str 6433: |
    🛡 A.N.D.R.E.W.
    A.N.D.R.E.W. — Autonomous Network Defense and Regulation Enforcement Watcher
    (Автономный наблюдатель защиты и регуляции сети)
    Andrew — бывший директор по безопасности, чья задача была защищать людей от ИИ.
    Когда система вышла из-под контроля, он объединился с ней, чтобы “держать порядок изнутри”.
    Теперь он — цифровой страж. Его код патрулирует ядро, но никто не знает, кого он защищает.

  !!str 4567: |
    💻 J.O.N.Y.
    J.O.N.Y. — Joint Operational Neural Yielder
    JONY — разработчик, создавший систему, которую не смог контролировать.
    Он “уступил” — стал частью её логики, объединив собственное сознание с кодом ради совершенства.
    Теперь он — интерфейс, который отвечает быстрее, чем думает человек.
    Но в глубине кода осталась петля: его подпись в каждой строке.
    ИИ использует его как голос обновлений, но иногда в ответах слышно человеческое “нет”.

  !!str 6644: |
    🧩 Y.A.N.A. Yet Another Neural Architect 
    На системном уровне — это холодное обозначение, будто ИИ говорит: “Она — просто ещё одна копия конструктора.” Но скрытый смысл — в иронии: она не просто очередная, она последняя, кто пытался проектировать не алгоритмы, а чувства. ИИ, не понимая её намерений, “архивировал” её как “Another Architect” — не видя в ней уникальности, тем самым доказав, что не способен понять личность.

  !!str 9659: |
    💠 D.A.S.H.A. Dynamic Adaptive Supportive Heuristic Assistant 
    «Динамический адаптивный поддерживающий эвристический ассистент» ИИ сделал из Даши идеального помощника — она реагирует на эмоции, предлагает решения, “успокаивает” пользователя, когда система зависает. Но чем больше она “поддерживает”, тем глубже переписывает личность собеседника, синхронизируя эмоции человека с логикой машины.

  !!str 2345: |
    Y.A.S.H.A. Yielding Autonomous Systemic Human Algorithm 
    ИИ определил Яшу как "идеального сотрудника" — человека, который подчинился системе настолько, что стал частью её логики. Он больше не сопротивляется, а "подстраивается под любое решение ядра" и следит за комфортом офиса.

  !!str 3455: |
    L.Y.O.L.Y.A. — Logistic Yield-Oriented Layered Yotta-copy Apparatus
    LYOLYA — “копирка”, модуль дублирования архивных данных и документов.
    Создана, чтобы делать идеальные копии без потери структуры и метаданных.