minio_host: minio.boxed-bots.ru
minio_secure: yes
minio_bucket: code-bot-2025

name: K.A.T.E Сис. авт. лог. настр. и хран. справ. мат.

start_message: |
  Привет! Я твой бот-помощник первого дня BootCamp! Я храню знания о всем, что связано с нашими работниками и офисами! Заходи в нужную комнату, введи код доступа сотрудника и я все тебе расскажу! 
  
  Хорошего рабочего дня!

default_message: |
  Система отключена или повреждена, повторите запрос позже

error_message: |
  Произошла ошибка 🥲

back_button: ⬅️ Назад
back_message: ⬅️ Вернулся назад

help_button: 🛟 Справка
help_message: Введите код с бейджика

node_codes:
  - name: "NODE: ECHO"
    code: "3657"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...

  - name: "NODE: SERENTY"
    code: "1538"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: AURORA"
    code: "6678"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: VOID"
    code: "3241"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Введите код доступа...
  
  - name: "NODE: RELEASE"
    code: "0985"
    content: audio_2025-10-29_23-58-35.ogg
    type: voice
    message: Данные повреждены, введите код восстановления логирования.

personal:
  Egor: |
    Егор Дубровин - хз кто это
  Tema: |
    Тема, весьма тёмная